CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(120) NOT NULL,
    isbn VARCHAR(20) NOT NULL,
    published_year INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_books_isbn UNIQUE (isbn),
    CONSTRAINT ck_books_published_year CHECK (published_year BETWEEN 1450 AND 2100)
);

CREATE TABLE book_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    operation VARCHAR(16) NOT NULL,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(120) NOT NULL,
    isbn VARCHAR(20) NOT NULL,
    published_year INTEGER NOT NULL,
    book_version BIGINT NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_book_history_operation
        CHECK (operation IN ('CREATED', 'UPDATED', 'DELETED')),
    CONSTRAINT ck_book_history_published_year
        CHECK (published_year BETWEEN 1450 AND 2100)
);

CREATE INDEX idx_book_history_book_changed
    ON book_history (book_id, changed_at DESC, id DESC);
