spring:
  application:
    name: biblioteca

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/biblioteca}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:biblioteca}
    password: ${DB_PASSWORD:biblioteca}

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
